import './global.css'
import {CitiesProvider} from "@/contexts/CitiesContext";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CitiesProvider>
          {children}
        </CitiesProvider>
      </body>
    </html>
  )
}
