'use client'

import './global.css'
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";
import {ReactQueryDevtools} from "@tanstack/react-query-devtools";
import {Suspense} from "react";
// @ts-ignore
import SpinnerFullPage from '@/components/ui/spinner-full-page/SpinnerFullPage';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 0
    }
  }
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <QueryClientProvider client={queryClient}>
        <ReactQueryDevtools initialIsOpen={false}/>
          <Suspense fallback={<SpinnerFullPage />}>
            {children}
          </Suspense>
      </QueryClientProvider>
      </body>
    </html>
  )
}
